### ISSUE TITLE
Update develop branch to be compatible with RxSwift 2.0 beta

### ISSUE THREAD

**Issue by gregpardo** [esttorhe/RxViewModel#8]
I might tackle this soon. Some of the changes include ObserverOf -> AnyObserver and such. Shouldn't be too bad.

**Comment by esttorhe** [comment]
:ok_hand: looking forward to that `PR` :)

**Comment by gregpardo** [comment]
Can you make a develop branch. Maybe I don't know how to do it but it's not letting me make a pull request because the branch doesn't exist.

**Comment by esttorhe** [comment]
Sure. Not on computer right now but will do it as soon as I get home. Thanks 

--
Esteban Torres
(+506)8813-0934
Twitter: @esttorhe




On Tue, Oct 20, 2015 at 2:30 PM -0700, "Greg Pardo" <notifications@github.com> wrote:












Can you make a develop branch. Maybe I don't know how to do it but it's not letting me make a pull request because the branch doesn't exist.

**Comment by esttorhe** [comment]
Here you go @gregpardo https://github.com/esttorhe/RxViewModel/tree/development
